[package]
name = "nvdb_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "nvdb_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
geo = "0.28"